# Generated by Django 4.2.8 on 2026-02-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_add_payment_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(
                db_index=True,
                max_length=100,
                null=True,
                blank=True,
                unique=False,
                help_text='Auto-generated unique bill number'
            ),
        ),
    ]
