# Generated by Django 4.2.8 on 2026-02-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_billsequence'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='billnumberlog',
            new_name='billing_bil_bill_nu_def6d2_idx',
            old_name='billing_bill_b_number_idx',
        ),
        migrations.RenameIndex(
            model_name='billnumberlog',
            new_name='billing_bil_used_17219e_idx',
            old_name='billing_bill_used_idx',
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated unique bill number', max_length=100, null=True, unique=True),
        ),
    ]
