# Generated by Django 4.2.8 on 2026-02-07 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLoyalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('loyalty_points', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('visits', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-loyalty_points'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI'), ('CHEQUE', 'Cheque'), ('WALLET', 'Digital Wallet'), ('CREDIT', 'Store Credit')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Payment Methods',
            },
        ),
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(max_length=100)),
                ('tax_type', models.CharField(choices=[('GST', 'GST (Goods and Service Tax)'), ('VAT', 'VAT (Value Added Tax)'), ('SALES_TAX', 'Sales Tax'), ('CUSTOM', 'Custom Tax')], max_length=20)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tax Configurations',
            },
        ),
        migrations.CreateModel(
            name='ShopConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='Grocery Store', max_length=255)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('receipt_header', models.TextField(blank=True, null=True)),
                ('receipt_footer', models.TextField(blank=True, null=True)),
                ('currency_symbol', models.CharField(default='₹', max_length=5)),
                ('low_stock_alert_level', models.IntegerField(default=10)),
                ('backup_enabled', models.BooleanField(default=True)),
                ('backup_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.taxconfiguration')),
            ],
            options={
                'verbose_name_plural': 'Shop Configuration',
            },
        ),
    ]
